services:
  ## shared services

  mysql:
    image: mysql:9.7.1
    # ports:
    #   - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./migrations/base.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql
    healthcheck:
      test: '/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  redis:
    image: redis:8.8.0
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}
    user: root
    env_file:
      - .env
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASS=${REDIS_PASS}
    command:
      - sh
      - -c
      - |
        if [ -n "$${REDIS_PASS}" ]; then
          redis-server --requirepass "$${REDIS_PASS}"
        else
          redis-server
        fi

  ## application services

  bancho:
    # we also have a public image: osuakatsuki/bancho.py:latest
    image: bancho:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    tty: true
    init: true
    env_file:
      - .env
    volumes:
      - .:/srv/root
      - data:/srv/root/.data

volumes:
  data:
  db-data:
  redis-data:
