name: Custom issue
description: This is mostly meant for project maintaners
title: "misc: "
labels: ["triage"]
assignees:
  - osuAkatsuki/bancho-py-devs
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!
  - type: textarea
    id: content
    attributes:
      label: Issue content
