from __future__ import annotations

from . import anticheat
from . import beatmap_sets
from . import beatmaps
from . import channels
from . import clans
from . import client_versioning
from . import comments
from . import direct
from . import error_reporting
from . import favourite_beatmap_sets
from . import geolocation
from . import mail
from . import mappools
from . import menus
from . import multiplayer
from . import nomination_requests
from . import notes
from . import performance
from . import players
from . import replays
from . import scores
from . import screenshots
