name: Test Application Code

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "**.sh"
      - "**.yml"
      - "**.toml"
      - "**.lock"
      - "**.sql"
      - "Dockerfile"
  pull_request:

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application image
        run: docker build -t bancho:latest .

      - name: Start containers
        run: docker compose --env-file .env.test -f docker-compose.test.yml up --detach --wait --wait-timeout 30 bancho-test mysql-test redis-test

      - name: Run tests
        run: docker compose --env-file .env.test -f docker-compose.test.yml exec -T bancho-test /srv/root/scripts/run-tests.sh

      - name: Stop containers
        if: always()
        run: docker compose --env-file .env.test -f docker-compose.test.yml down --volumes --remove-orphans

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/
